import Foundation

/// A file shown with a message: uploaded by the user or generated by the model.
public struct AttachmentReference: Hashable, Sendable, Identifiable {
    public let id: String
    public let name: String
    public let mimeType: String
    public let generated: Bool

    public var isImage: Bool { mimeType.hasPrefix("image/") }
}

/// A step the model took before answering: a tool call, the agent workspace,
/// recalled chats, or context compaction.
public struct ActivityItem: Hashable, Sendable, Identifiable {
    public enum Kind: String, Sendable {
        case tool, workspace, recall, compaction
    }

    public let id: String
    public let kind: Kind
    public let title: String
    public let detail: String
    public let status: String
    public let durationMs: Int?

    public var isRunning: Bool { ["queued", "running", "in_progress", "starting", "waiting"].contains(status) }
    public var isFailed: Bool { status == "failed" }
}

/// Display projection of a response's output items.
public struct ResponseContent: Hashable, Sendable {
    public var text: String
    public var reasoning: String?
    /// Duration reported by the model's reasoning items, in milliseconds.
    public var reasoningDurationMs: Int?
    public var activities: [ActivityItem]
    public var attachments: [AttachmentReference]

    public init(output: [JSONValue]) {
        text = output
            .filter { $0["type"]?.stringValue == "message" }
            .map { Self.text(from: $0["content"]) }
            .filter { !$0.isEmpty }
            .joined(separator: "\n\n")
        let reasoningItems = output.filter { $0["type"]?.stringValue == "reasoning" }
        let reasoningText = reasoningItems
            .map { Self.text(from: $0["summary"]) }
            .filter { !$0.isEmpty }
            .joined(separator: "\n\n")
        reasoning = reasoningText.isEmpty ? nil : reasoningText
        let durations = reasoningItems.compactMap { $0["durationMs"]?.millisecondsValue }
        reasoningDurationMs = durations.isEmpty ? nil : durations.reduce(0, +)
        activities = output.enumerated().compactMap { Self.activity($1, index: $0) }
        attachments = output.compactMap { item in
            guard item["type"]?.stringValue == "pulpo_attachment",
                  let id = item["attachment_id"]?.stringValue else { return nil }
            return AttachmentReference(
                id: id,
                name: item["name"]?.stringValue ?? "Generated file",
                mimeType: item["mime_type"]?.stringValue ?? "application/octet-stream",
                generated: true
            )
        }
    }

    public var isEmpty: Bool {
        text.isEmpty && reasoning == nil && activities.isEmpty && attachments.isEmpty
    }

    static func text(from content: JSONValue?) -> String {
        guard let content else { return "" }
        if let text = content.stringValue { return text }
        return (content.arrayValue ?? []).map { part in
            if let text = part.stringValue { return text }
            return (part["text"] ?? part["content"] ?? part["refusal"])?.stringValue ?? ""
        }.joined()
    }

    private static func activity(_ item: JSONValue, index: Int) -> ActivityItem? {
        let id = item["id"]?.stringValue
        let duration = item["durationMs"]?.millisecondsValue ?? item["duration_ms"]?.millisecondsValue
        switch item["type"]?.stringValue {
        case "pulpo_tool":
            let tool = item["tool"]?.stringValue ?? "tool"
            return ActivityItem(
                id: id ?? "tool-\(index)", kind: .tool, title: ToolNames.describe(tool),
                detail: item["output"]?.stringValue ?? "", status: item["status"]?.stringValue ?? "running",
                durationMs: duration
            )
        case "pulpo_workspace":
            let state = item["state"]?.stringValue ?? "running"
            return ActivityItem(
                id: id ?? "workspace-\(index)", kind: .workspace, title: "Agent workspace",
                detail: item["error"]?.stringValue ?? state, status: state, durationMs: duration
            )
        case "pulpo_recall":
            let sources = item["sources"]?.arrayValue ?? []
            return ActivityItem(
                id: id ?? "recall-\(index)", kind: .recall,
                title: "Recalled from \(sources.count) \(sources.count == 1 ? "chat" : "chats")",
                detail: sources.compactMap { $0["title"]?.stringValue }.joined(separator: ", "),
                status: "completed", durationMs: nil
            )
        case "pulpo_compaction":
            let status = item["status"]?.stringValue ?? "in_progress"
            let title = switch status {
            case "in_progress": "Compacting context…"
            case "failed": "Context compaction failed"
            default: "Compacted context"
            }
            return ActivityItem(
                id: id ?? "compaction-\(index)", kind: .compaction, title: title,
                detail: item["summary"]?.stringValue ?? "", status: status, durationMs: duration
            )
        default:
            return nil
        }
    }
}

/// Friendly labels for agent tools.
enum ToolNames {
    static func describe(_ tool: String) -> String {
        switch tool {
        case "web_search", "search": "Searched the web"
        case "web_fetch", "fetch", "open_url": "Read a web page"
        case "bash", "shell", "run_command", "exec": "Ran a command"
        case "python", "run_code", "code_interpreter": "Ran code"
        case "read_file", "read": "Read a file"
        case "write_file", "write", "edit_file", "edit", "apply_patch": "Edited a file"
        case "list_files", "ls", "glob": "Listed files"
        case "image_generation", "generate_image": "Generated an image"
        default:
            tool.replacingOccurrences(of: "_", with: " ").capitalizedFirstLetter
        }
    }
}

public struct BranchPosition: Hashable, Sendable {
    public let ids: [String]
    public let index: Int

    public init(ids: [String], index: Int) {
        self.ids = ids
        self.index = index
    }

    public var count: Int { ids.count }
    public var hasSiblings: Bool { ids.count > 1 }
    public var previous: String? { index > 0 ? ids[index - 1] : nil }
    public var next: String? { index + 1 < ids.count ? ids[index + 1] : nil }
}

/// One rendered exchange: the user's message and the reply to it.
public struct TranscriptTurn: Hashable, Sendable, Identifiable {
    public let id: String
    public let userText: String
    public let userAttachments: [AttachmentReference]
    public let modelId: String
    public let createdAt: Date
    public let completedAt: Date?
    public let status: ResponseStatus
    public let content: ResponseContent
    public let errorMessage: String?
    public let userBranch: BranchPosition?
    public let assistantBranch: BranchPosition?
    /// Time from the request until the first reply text: how long the model "thought".
    public let thinkingDuration: TimeInterval?

    public var isActive: Bool { status.isActive }
    public var isCancelled: Bool { status == .cancelled }
}

public enum Transcript {
    /// Walks the active branch from its leaf to the root, oldest first.
    public static func lineage(_ responses: [ChatResponse], leafId: String?) -> [ChatResponse] {
        let byId = Dictionary(responses.map { ($0.id, $0) }, uniquingKeysWith: { _, last in last })
        var result: [ChatResponse] = []
        var seen = Set<String>()
        var cursor = leafId
        while let id = cursor, seen.insert(id).inserted, let node = byId[id] {
            result.append(node)
            cursor = node.parentResponseId
        }
        return result.reversed()
    }

    /// The newest leaf below `id`, following the last child in server order.
    public static func newestDescendant(of id: String, in responses: [ChatResponse]) -> String {
        var newestChild: [String: String] = [:]
        for response in responses {
            if let parent = response.parentResponseId { newestChild[parent] = response.id }
        }
        var leaf = id
        var seen: Set<String> = [id]
        while let next = newestChild[leaf], seen.insert(next).inserted { leaf = next }
        return leaf
    }

    public static func leafId(of detail: ChatDetail) -> String? {
        detail.activeBranchLeafId ?? detail.activeResponseId ?? detail.responses.last?.id
    }

    /// Projects the chat's active branch, folding in live realtime snapshots.
    public static func turns(for detail: ChatDetail, live: [String: ResponseSnapshot] = [:]) -> [TranscriptTurn] {
        let attachments = Dictionary(detail.attachments.map { ($0.id, $0) }, uniquingKeysWith: { _, last in last })
        return lineage(detail.responses, leafId: leafId(of: detail))
            .filter(\.detailAvailable)
            .map { response in
                var snapshot = response.liveSnapshot
                if let live = live[response.id] { snapshot = ResponseReducer.merge(snapshot, live) }
                let inputFiles = inputAttachmentIds(response.input).compactMap { id in
                    attachments[id].map {
                        AttachmentReference(id: $0.id, name: $0.originalName, mimeType: $0.mimeType, generated: false)
                    }
                }
                return TranscriptTurn(
                    id: response.id,
                    userText: inputText(response.input),
                    userAttachments: inputFiles,
                    modelId: response.shownModelId,
                    createdAt: response.createdAt,
                    completedAt: response.completedAt,
                    status: snapshot.status,
                    content: ResponseContent(output: snapshot.output),
                    errorMessage: snapshot.status == .cancelled ? nil : snapshot.errorMessage,
                    userBranch: response.branches?.user.map { BranchPosition(ids: $0.ids, index: $0.index) },
                    assistantBranch: response.branches?.assistant.map { BranchPosition(ids: $0.ids, index: $0.index) },
                    thinkingDuration: thinkingDuration(snapshot)
                )
            }
    }

    /// The text of the last user item in a response's input.
    public static func inputText(_ input: [JSONValue]) -> String {
        for item in input.reversed() where item["role"]?.stringValue == "user" {
            return ResponseContent.text(from: item["content"])
        }
        return ""
    }

    static func inputAttachmentIds(_ input: [JSONValue]) -> [String] {
        input.flatMap { item in
            (item["content"]?.arrayValue ?? []).compactMap { part in
                part["type"]?.stringValue == "input_file" ? part["attachment_id"]?.stringValue : nil
            }
        }
    }

    static func thinkingDuration(_ snapshot: ResponseSnapshot) -> TimeInterval? {
        guard let start = snapshot.requestReceivedAt.flatMap(PulpoDate.parse),
              let end = snapshot.firstReplyTextAt.flatMap(PulpoDate.parse)
        else { return nil }
        return max(0, end.timeIntervalSince(start))
    }
}

extension String {
    var capitalizedFirstLetter: String {
        guard let first else { return self }
        return first.uppercased() + dropFirst()
    }
}
