import { Platform, type ColorValue } from 'react-native';
import { SymbolView, type SymbolViewProps } from 'expo-symbols';
import {
  AtSign,
  ArrowUpDown,
  Bookmark,
  Brain,
  Camera,
  Check,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleStop,
  CircleX,
  ClockAlert,
  Copy,
  Eye,
  EyeOff,
  File,
  FileSearch,
  FolderPlus,
  Folder,
  FolderOpen,
  HardDrive,
  Hourglass,
  ImageOff,
  Images,
  Info,
  KeyRound,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageCircle,
  Network,
  PanelsTopLeft,
  Pencil,
  Plus,
  QrCode,
  RefreshCw,
  Reply,
  Search,
  Server,
  Settings,
  Share2,
  ShieldCheck,
  ShieldOff,
  SlidersHorizontal,
  Smartphone,
  SquarePen,
  Star,
  Trash2,
  TriangleAlert,
  User,
  X,
  type LucideIcon,
} from 'lucide-react-native';

const ANDROID_ICONS: Record<string, LucideIcon> = {
  'arrow.clockwise': RefreshCw,
  'arrow.up.arrow.down': ArrowUpDown,
  'arrowshape.turn.up.left': Reply,
  at: AtSign,
  'brain.head.profile': Brain,
  bookmark: Bookmark,
  'bubble.left': MessageCircle,
  checkmark: Check,
  'checkmark.circle.fill': CircleCheck,
  'checkmark.shield': ShieldCheck,
  camera: Camera,
  'chevron.left': ChevronLeft,
  'chevron.right': ChevronRight,
  'circle.lefthalf.filled': Circle,
  'clock.badge.xmark': ClockAlert,
  'doc.fill': File,
  'doc.on.doc': Copy,
  'doc.text.magnifyingglass': FileSearch,
  envelope: Mail,
  externaldrive: HardDrive,
  'exclamationmark.circle.fill': CircleAlert,
  'exclamationmark.triangle': TriangleAlert,
  'exclamationmark.triangle.fill': TriangleAlert,
  eye: Eye,
  'eye.slash': EyeOff,
  folder: Folder,
  'folder.badge.plus': FolderPlus,
  'folder.fill': FolderOpen,
  hourglass: Hourglass,
  'info.circle': Info,
  gearshape: Settings,
  'iphone.radiowaves.left.and.right': Smartphone,
  lock: Lock,
  'lock.rotation': Lock,
  'line.3.horizontal': Menu,
  magnifyingglass: Search,
  network: Network,
  pencil: Pencil,
  'person.badge.key': KeyRound,
  'person.crop.circle': User,
  'person.crop.circle.badge.clock': User,
  'photo.badge.exclamationmark': ImageOff,
  'photo.on.rectangle': Images,
  plus: Plus,
  qrcode: QrCode,
  'rectangle.3.group': PanelsTopLeft,
  'questionmark.circle': CircleHelp,
  'rectangle.portrait.and.arrow.right': LogOut,
  'server.rack': Server,
  'square.and.arrow.up': Share2,
  'shield.slash': ShieldOff,
  'slider.horizontal.3': SlidersHorizontal,
  'square.and.pencil': SquarePen,
  star: Star,
  'stop.circle': CircleStop,
  trash: Trash2,
  'trash.slash': Trash2,
  xmark: X,
  'xmark.circle.fill': CircleX,
};

export function PlatformIcon({ name, size, color, weight = 'regular' }: {
  name: string;
  size: number;
  color: ColorValue;
  weight?: SymbolViewProps['weight'];
}) {
  if (Platform.OS !== 'android') {
    return <SymbolView name={name as never} size={size} tintColor={color} weight={weight} />;
  }
  const AndroidIcon = ANDROID_ICONS[name] ?? Circle;
  return <AndroidIcon color={color} size={size} strokeWidth={weight === 'bold' || weight === 'semibold' ? 2.5 : 2} />;
}
